# Generated by Django 4.2.6 on 2023-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=150)),
                ('no_of_cameras', models.BigIntegerField()),
                ('mobile_ram', models.CharField(max_length=100)),
                ('mobile_price', models.BigIntegerField()),
                ('mobile_color', models.CharField(max_length=150)),
            ],
        ),
    ]
